### ISSUE TITLE
PostrgreSQL JSONB Support

### ISSUE THREAD

**Issue by robbydf** [gofabian/spring-boot-data-r2dbc-jooq#22] opened 2020-08-15 05:04 UTC
I've been trying to convert my jooq based application from jdbc to r2dbc using this library. However I encountered an issue regarding r2dbc-postgresql. Here is the response of Netty to one of my select queries to the database containing one JSONB data type in PostgreSQL.

`{
  "timestamp": "time_stamp_here",
  "path": "request_path_here",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Cannot convert from JsonOutput{{database_json_content_ere}} (class io.r2dbc.postgresql.codec.Json$JsonOutput) to class org.jooq.JSONB",
  "requestId": "request_id_here"
}`

Any ideas on how to fix this?

**Comment by robbydf** [comment] 2020-08-15 08:35
Added support via pull request #23 

Comments and edits are welcome

**Comment by gofabian** [comment] 2020-12-19 09:45
The problem is that the JSON-Types of r2dbc-postgresql (`io.r2dbc.postgresql.codec.Json`) and JOOQ (`org.jooq.JSON`, `org.jooq.JSONB`) are not compatible. Both are able to cope with Strings but they have their own JSON data classes used by default.

In our next release we will have a `Converter` class that is an adapter between R2DBC driver and JOOQ. We will provide JSON support with r2dbc-mysql and r2dbc-postgresql out-of-the-box.

**Comment by gofabian** [comment] 2020-12-19 12:56
Closing in favor of https://github.com/gofabian/spring-boot-data-r2dbc-jooq/issues/26

**Closed by gofabian** 2020-12-19 12:56 UTC
Labels: question
